server:
  port: 8080

spring:
  application:
    name: stocktracker-service
  data:
    mongodb:
      #uri: uri-cloud
      host: localhost
      port: 27017
      database: stocktracker
    redis:
      host: localhost
      port: 6379
      password: sa
      timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 100
  cache:
    redis:
      time-to-live: 60000

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger/index.html

stock:
  client:
    brapi:
      url: https://brapi.dev/api/quote
      token: 9MGuepVVhLRAmNfaEzE69z

security:
  securityLoginKey: 'secret-key'